<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="HotelDataSet" targetNamespace="http://tempuri.org/HotelDataSet.xsd" xmlns:mstns="http://tempuri.org/HotelDataSet.xsd" xmlns="http://tempuri.org/HotelDataSet.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:annotation>
    <xs:appinfo source="urn:schemas-microsoft-com:xml-msdatasource">
      <DataSource DefaultConnectionIndex="0" FunctionsComponentName="QueriesTableAdapter" Modifier="AutoLayout, AnsiClass, Class, Public" SchemaSerializationMode="IncludeSchema" xmlns="urn:schemas-microsoft-com:xml-msdatasource">
        <Connections>
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="HotelConnectionString" ConnectionStringObject="" IsAppSettingsProperty="true" Modifier="Assembly" Name="HotelConnectionString (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.HotelApp.Properties.Settings.GlobalReference.Default.HotelConnectionString" Provider="System.Data.SqlClient" />
        </Connections>
        <Tables>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="GenderTableAdapter" GeneratorDataComponentClassName="GenderTableAdapter" Name="Gender" UserDataComponentName="GenderTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.Gender" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[Gender] WHERE (([IdGender] = @Original_IdGender) AND ([GenderName] = @Original_GenderName))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdGender" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdGender" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_GenderName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="GenderName" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[Gender] ([GenderName]) VALUES (@GenderName);
SELECT IdGender, GenderName FROM Gender WHERE (IdGender = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@GenderName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="GenderName" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdGender, GenderName FROM dbo.Gender</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[Gender] SET [GenderName] = @GenderName WHERE (([IdGender] = @Original_IdGender) AND ([GenderName] = @Original_GenderName));
SELECT IdGender, GenderName FROM Gender WHERE (IdGender = @IdGender)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@GenderName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="GenderName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdGender" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdGender" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_GenderName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="GenderName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdGender" ColumnName="IdGender" DataSourceName="Hotel.dbo.Gender" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdGender" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdGender" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdGender" DataSetColumn="IdGender" />
              <Mapping SourceColumn="GenderName" DataSetColumn="GenderName" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="GuestTableAdapter" GeneratorDataComponentClassName="GuestTableAdapter" Name="Guest" UserDataComponentName="GuestTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.Guest" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[Guest] WHERE (([IdGuest] = @Original_IdGuest) AND ([FullName] = @Original_FullName) AND ([Birthday] = @Original_Birthday) AND ([GenderId] = @Original_GenderId) AND ([StatusId] = @Original_StatusId))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdGuest" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdGuest" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_FullName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="FullName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_Birthday" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="Birthday" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_GenderId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GenderId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_StatusId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="StatusId" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[Guest] ([FullName], [Birthday], [GenderId], [StatusId]) VALUES (@FullName, @Birthday, @GenderId, @StatusId);
SELECT IdGuest, FullName, Birthday, GenderId, StatusId FROM Guest WHERE (IdGuest = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@FullName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="FullName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Birthday" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="Birthday" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@GenderId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GenderId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@StatusId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="StatusId" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdGuest, FullName, Birthday, GenderId, StatusId FROM dbo.Guest</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[Guest] SET [FullName] = @FullName, [Birthday] = @Birthday, [GenderId] = @GenderId, [StatusId] = @StatusId WHERE (([IdGuest] = @Original_IdGuest) AND ([FullName] = @Original_FullName) AND ([Birthday] = @Original_Birthday) AND ([GenderId] = @Original_GenderId) AND ([StatusId] = @Original_StatusId));
SELECT IdGuest, FullName, Birthday, GenderId, StatusId FROM Guest WHERE (IdGuest = @IdGuest)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@FullName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="FullName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Birthday" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="Birthday" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@GenderId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GenderId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@StatusId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="StatusId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdGuest" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdGuest" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_FullName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="FullName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_Birthday" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="Birthday" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_GenderId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GenderId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_StatusId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="StatusId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdGuest" ColumnName="IdGuest" DataSourceName="Hotel.dbo.Guest" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdGuest" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdGuest" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdGuest" DataSetColumn="IdGuest" />
              <Mapping SourceColumn="FullName" DataSetColumn="FullName" />
              <Mapping SourceColumn="Birthday" DataSetColumn="Birthday" />
              <Mapping SourceColumn="GenderId" DataSetColumn="GenderId" />
              <Mapping SourceColumn="StatusId" DataSetColumn="StatusId" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="HistoryTableAdapter" GeneratorDataComponentClassName="HistoryTableAdapter" Name="History" UserDataComponentName="HistoryTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.History" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[History] WHERE (([IdHistory] = @Original_IdHistory) AND ([GuestId] = @Original_GuestId) AND ([RoomId] = @Original_RoomId) AND ([CheckIn] = @Original_CheckIn) AND ([CheckOut] = @Original_CheckOut))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdHistory" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdHistory" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_GuestId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GuestId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_RoomId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_CheckIn" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckIn" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_CheckOut" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckOut" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[History] ([GuestId], [RoomId], [CheckIn], [CheckOut], [Comment]) VALUES (@GuestId, @RoomId, @CheckIn, @CheckOut, @Comment);
SELECT IdHistory, GuestId, RoomId, CheckIn, CheckOut, Comment FROM History WHERE (IdHistory = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@GuestId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GuestId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@RoomId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@CheckIn" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckIn" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@CheckOut" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckOut" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="true" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Comment" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="Comment" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdHistory, GuestId, RoomId, CheckIn, CheckOut, Comment FROM dbo.History</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[History] SET [GuestId] = @GuestId, [RoomId] = @RoomId, [CheckIn] = @CheckIn, [CheckOut] = @CheckOut, [Comment] = @Comment WHERE (([IdHistory] = @Original_IdHistory) AND ([GuestId] = @Original_GuestId) AND ([RoomId] = @Original_RoomId) AND ([CheckIn] = @Original_CheckIn) AND ([CheckOut] = @Original_CheckOut));
SELECT IdHistory, GuestId, RoomId, CheckIn, CheckOut, Comment FROM History WHERE (IdHistory = @IdHistory)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@GuestId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GuestId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@RoomId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@CheckIn" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckIn" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@CheckOut" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckOut" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="true" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Comment" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="Comment" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdHistory" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdHistory" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_GuestId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="GuestId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_RoomId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_CheckIn" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckIn" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Date" Direction="Input" ParameterName="@Original_CheckOut" Precision="0" ProviderType="Date" Scale="0" Size="0" SourceColumn="CheckOut" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdHistory" ColumnName="IdHistory" DataSourceName="Hotel.dbo.History" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdHistory" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdHistory" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdHistory" DataSetColumn="IdHistory" />
              <Mapping SourceColumn="GuestId" DataSetColumn="GuestId" />
              <Mapping SourceColumn="RoomId" DataSetColumn="RoomId" />
              <Mapping SourceColumn="CheckIn" DataSetColumn="CheckIn" />
              <Mapping SourceColumn="CheckOut" DataSetColumn="CheckOut" />
              <Mapping SourceColumn="Comment" DataSetColumn="Comment" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="HotelTableAdapter" GeneratorDataComponentClassName="HotelTableAdapter" Name="Hotel" UserDataComponentName="HotelTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.Hotel" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[Hotel] WHERE (([IdHotel] = @Original_IdHotel) AND ([HotelName] = @Original_HotelName))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdHotel" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdHotel" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_HotelName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="HotelName" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[Hotel] ([HotelName]) VALUES (@HotelName);
SELECT IdHotel, HotelName FROM Hotel WHERE (IdHotel = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@HotelName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="HotelName" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdHotel, HotelName FROM dbo.Hotel</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[Hotel] SET [HotelName] = @HotelName WHERE (([IdHotel] = @Original_IdHotel) AND ([HotelName] = @Original_HotelName));
SELECT IdHotel, HotelName FROM Hotel WHERE (IdHotel = @IdHotel)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@HotelName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="HotelName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdHotel" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdHotel" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_HotelName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="HotelName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdHotel" ColumnName="IdHotel" DataSourceName="Hotel.dbo.Hotel" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdHotel" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdHotel" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdHotel" DataSetColumn="IdHotel" />
              <Mapping SourceColumn="HotelName" DataSetColumn="HotelName" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="RoomTableAdapter" GeneratorDataComponentClassName="RoomTableAdapter" Name="Room" UserDataComponentName="RoomTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.Room" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[Room] WHERE (([IdRoom] = @Original_IdRoom) AND ([Number] = @Original_Number) AND ([RoomTypeId] = @Original_RoomTypeId) AND ([HotelId] = @Original_HotelId))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdRoom" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdRoom" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_Number" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="Number" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_RoomTypeId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomTypeId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_HotelId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="HotelId" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[Room] ([Number], [RoomTypeId], [HotelId]) VALUES (@Number, @RoomTypeId, @HotelId);
SELECT IdRoom, Number, RoomTypeId, HotelId FROM Room WHERE (IdRoom = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Number" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="Number" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@RoomTypeId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomTypeId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@HotelId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="HotelId" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdRoom, Number, RoomTypeId, HotelId FROM dbo.Room</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[Room] SET [Number] = @Number, [RoomTypeId] = @RoomTypeId, [HotelId] = @HotelId WHERE (([IdRoom] = @Original_IdRoom) AND ([Number] = @Original_Number) AND ([RoomTypeId] = @Original_RoomTypeId) AND ([HotelId] = @Original_HotelId));
SELECT IdRoom, Number, RoomTypeId, HotelId FROM Room WHERE (IdRoom = @IdRoom)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Number" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="Number" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@RoomTypeId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomTypeId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@HotelId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="HotelId" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdRoom" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdRoom" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_Number" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="Number" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_RoomTypeId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="RoomTypeId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_HotelId" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="HotelId" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdRoom" ColumnName="IdRoom" DataSourceName="Hotel.dbo.Room" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdRoom" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdRoom" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdRoom" DataSetColumn="IdRoom" />
              <Mapping SourceColumn="Number" DataSetColumn="Number" />
              <Mapping SourceColumn="RoomTypeId" DataSetColumn="RoomTypeId" />
              <Mapping SourceColumn="HotelId" DataSetColumn="HotelId" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="RoomTypeTableAdapter" GeneratorDataComponentClassName="RoomTypeTableAdapter" Name="RoomType" UserDataComponentName="RoomTypeTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.RoomType" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[RoomType] WHERE (([IdRoomType] = @Original_IdRoomType) AND ([RoomTypeName] = @Original_RoomTypeName))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdRoomType" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdRoomType" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_RoomTypeName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="RoomTypeName" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[RoomType] ([RoomTypeName]) VALUES (@RoomTypeName);
SELECT IdRoomType, RoomTypeName FROM RoomType WHERE (IdRoomType = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@RoomTypeName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="RoomTypeName" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdRoomType, RoomTypeName FROM dbo.RoomType</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[RoomType] SET [RoomTypeName] = @RoomTypeName WHERE (([IdRoomType] = @Original_IdRoomType) AND ([RoomTypeName] = @Original_RoomTypeName));
SELECT IdRoomType, RoomTypeName FROM RoomType WHERE (IdRoomType = @IdRoomType)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@RoomTypeName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="RoomTypeName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdRoomType" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdRoomType" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_RoomTypeName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="RoomTypeName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdRoomType" ColumnName="IdRoomType" DataSourceName="Hotel.dbo.RoomType" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdRoomType" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdRoomType" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdRoomType" DataSetColumn="IdRoomType" />
              <Mapping SourceColumn="RoomTypeName" DataSetColumn="RoomTypeName" />
            </Mappings>
            <Sources />
          </TableAdapter>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="StatusTableAdapter" GeneratorDataComponentClassName="StatusTableAdapter" Name="Status" UserDataComponentName="StatusTableAdapter">
            <MainSource>
              <DbSource ConnectionRef="HotelConnectionString (Settings)" DbObjectName="Hotel.dbo.Status" DbObjectType="Table" FillMethodModifier="Public" FillMethodName="Fill" GenerateMethods="Both" GenerateShortCommands="true" GeneratorGetMethodName="GetData" GeneratorSourceName="Fill" GetMethodModifier="Public" GetMethodName="GetData" QueryType="Rowset" ScalarCallRetval="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" UseOptimisticConcurrency="true" UserGetMethodName="GetData" UserSourceName="Fill">
                <DeleteCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>DELETE FROM [dbo].[Status] WHERE (([IdStatus] = @Original_IdStatus) AND ([StatusName] = @Original_StatusName))</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdStatus" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdStatus" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_StatusName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="StatusName" SourceColumnNullMapping="false" SourceVersion="Original" />
                    </Parameters>
                  </DbCommand>
                </DeleteCommand>
                <InsertCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>INSERT INTO [dbo].[Status] ([StatusName]) VALUES (@StatusName);
SELECT IdStatus, StatusName FROM Status WHERE (IdStatus = SCOPE_IDENTITY())</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@StatusName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="StatusName" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </InsertCommand>
                <SelectCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>SELECT IdStatus, StatusName FROM dbo.Status</CommandText>
                    <Parameters />
                  </DbCommand>
                </SelectCommand>
                <UpdateCommand>
                  <DbCommand CommandType="Text" ModifiedByUser="false">
                    <CommandText>UPDATE [dbo].[Status] SET [StatusName] = @StatusName WHERE (([IdStatus] = @Original_IdStatus) AND ([StatusName] = @Original_StatusName));
SELECT IdStatus, StatusName FROM Status WHERE (IdStatus = @IdStatus)</CommandText>
                    <Parameters>
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@StatusName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="StatusName" SourceColumnNullMapping="false" SourceVersion="Current" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="Int32" Direction="Input" ParameterName="@Original_IdStatus" Precision="0" ProviderType="Int" Scale="0" Size="0" SourceColumn="IdStatus" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="" DataSourceName="" DbType="String" Direction="Input" ParameterName="@Original_StatusName" Precision="0" ProviderType="NVarChar" Scale="0" Size="0" SourceColumn="StatusName" SourceColumnNullMapping="false" SourceVersion="Original" />
                      <Parameter AllowDbNull="false" AutogeneratedName="IdStatus" ColumnName="IdStatus" DataSourceName="Hotel.dbo.Status" DataTypeServer="int" DbType="Int32" Direction="Input" ParameterName="@IdStatus" Precision="0" ProviderType="Int" Scale="0" Size="4" SourceColumn="IdStatus" SourceColumnNullMapping="false" SourceVersion="Current" />
                    </Parameters>
                  </DbCommand>
                </UpdateCommand>
              </DbSource>
            </MainSource>
            <Mappings>
              <Mapping SourceColumn="IdStatus" DataSetColumn="IdStatus" />
              <Mapping SourceColumn="StatusName" DataSetColumn="StatusName" />
            </Mappings>
            <Sources />
          </TableAdapter>
        </Tables>
        <Sources />
      </DataSource>
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="HotelDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true" msprop:EnableTableAdapterManager="True" msprop:Generator_UserDSName="HotelDataSet" msprop:Generator_DataSetName="HotelDataSet">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Gender" msprop:Generator_RowEvHandlerName="GenderRowChangeEventHandler" msprop:Generator_RowDeletedName="GenderRowDeleted" msprop:Generator_RowDeletingName="GenderRowDeleting" msprop:Generator_RowEvArgName="GenderRowChangeEvent" msprop:Generator_TablePropName="Gender" msprop:Generator_RowChangedName="GenderRowChanged" msprop:Generator_RowChangingName="GenderRowChanging" msprop:Generator_TableClassName="GenderDataTable" msprop:Generator_RowClassName="GenderRow" msprop:Generator_TableVarName="tableGender" msprop:Generator_UserTableName="Gender">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdGender" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdGender" msprop:Generator_ColumnPropNameInTable="IdGenderColumn" msprop:Generator_ColumnVarNameInTable="columnIdGender" msprop:Generator_UserColumnName="IdGender" type="xs:int" />
              <xs:element name="GenderName" msprop:Generator_ColumnPropNameInRow="GenderName" msprop:Generator_ColumnPropNameInTable="GenderNameColumn" msprop:Generator_ColumnVarNameInTable="columnGenderName" msprop:Generator_UserColumnName="GenderName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Guest" msprop:Generator_RowEvHandlerName="GuestRowChangeEventHandler" msprop:Generator_RowDeletedName="GuestRowDeleted" msprop:Generator_RowDeletingName="GuestRowDeleting" msprop:Generator_RowEvArgName="GuestRowChangeEvent" msprop:Generator_TablePropName="Guest" msprop:Generator_RowChangedName="GuestRowChanged" msprop:Generator_RowChangingName="GuestRowChanging" msprop:Generator_TableClassName="GuestDataTable" msprop:Generator_RowClassName="GuestRow" msprop:Generator_TableVarName="tableGuest" msprop:Generator_UserTableName="Guest">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdGuest" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdGuest" msprop:Generator_ColumnPropNameInTable="IdGuestColumn" msprop:Generator_ColumnVarNameInTable="columnIdGuest" msprop:Generator_UserColumnName="IdGuest" type="xs:int" />
              <xs:element name="FullName" msprop:Generator_ColumnPropNameInRow="FullName" msprop:Generator_ColumnPropNameInTable="FullNameColumn" msprop:Generator_ColumnVarNameInTable="columnFullName" msprop:Generator_UserColumnName="FullName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="150" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Birthday" msprop:Generator_ColumnPropNameInRow="Birthday" msprop:Generator_ColumnPropNameInTable="BirthdayColumn" msprop:Generator_ColumnVarNameInTable="columnBirthday" msprop:Generator_UserColumnName="Birthday" type="xs:dateTime" />
              <xs:element name="GenderId" msprop:Generator_ColumnPropNameInRow="GenderId" msprop:Generator_ColumnPropNameInTable="GenderIdColumn" msprop:Generator_ColumnVarNameInTable="columnGenderId" msprop:Generator_UserColumnName="GenderId" type="xs:int" />
              <xs:element name="StatusId" msprop:Generator_ColumnPropNameInRow="StatusId" msprop:Generator_ColumnPropNameInTable="StatusIdColumn" msprop:Generator_ColumnVarNameInTable="columnStatusId" msprop:Generator_UserColumnName="StatusId" type="xs:int" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="History" msprop:Generator_RowEvHandlerName="HistoryRowChangeEventHandler" msprop:Generator_RowDeletedName="HistoryRowDeleted" msprop:Generator_RowDeletingName="HistoryRowDeleting" msprop:Generator_RowEvArgName="HistoryRowChangeEvent" msprop:Generator_TablePropName="History" msprop:Generator_RowChangedName="HistoryRowChanged" msprop:Generator_RowChangingName="HistoryRowChanging" msprop:Generator_TableClassName="HistoryDataTable" msprop:Generator_RowClassName="HistoryRow" msprop:Generator_TableVarName="tableHistory" msprop:Generator_UserTableName="History">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdHistory" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdHistory" msprop:Generator_ColumnPropNameInTable="IdHistoryColumn" msprop:Generator_ColumnVarNameInTable="columnIdHistory" msprop:Generator_UserColumnName="IdHistory" type="xs:int" />
              <xs:element name="GuestId" msprop:Generator_ColumnPropNameInRow="GuestId" msprop:Generator_ColumnPropNameInTable="GuestIdColumn" msprop:Generator_ColumnVarNameInTable="columnGuestId" msprop:Generator_UserColumnName="GuestId" type="xs:int" />
              <xs:element name="RoomId" msprop:Generator_ColumnPropNameInRow="RoomId" msprop:Generator_ColumnPropNameInTable="RoomIdColumn" msprop:Generator_ColumnVarNameInTable="columnRoomId" msprop:Generator_UserColumnName="RoomId" type="xs:int" />
              <xs:element name="CheckIn" msprop:Generator_ColumnPropNameInRow="CheckIn" msprop:Generator_ColumnPropNameInTable="CheckInColumn" msprop:Generator_ColumnVarNameInTable="columnCheckIn" msprop:Generator_UserColumnName="CheckIn" type="xs:dateTime" />
              <xs:element name="CheckOut" msprop:Generator_ColumnPropNameInRow="CheckOut" msprop:Generator_ColumnPropNameInTable="CheckOutColumn" msprop:Generator_ColumnVarNameInTable="columnCheckOut" msprop:Generator_UserColumnName="CheckOut" type="xs:dateTime" />
              <xs:element name="Comment" msprop:Generator_ColumnPropNameInRow="Comment" msprop:Generator_ColumnPropNameInTable="CommentColumn" msprop:Generator_ColumnVarNameInTable="columnComment" msprop:Generator_UserColumnName="Comment" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="2147483647" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Hotel" msprop:Generator_RowEvHandlerName="HotelRowChangeEventHandler" msprop:Generator_RowDeletedName="HotelRowDeleted" msprop:Generator_RowDeletingName="HotelRowDeleting" msprop:Generator_RowEvArgName="HotelRowChangeEvent" msprop:Generator_TablePropName="Hotel" msprop:Generator_RowChangedName="HotelRowChanged" msprop:Generator_RowChangingName="HotelRowChanging" msprop:Generator_TableClassName="HotelDataTable" msprop:Generator_RowClassName="HotelRow" msprop:Generator_TableVarName="tableHotel" msprop:Generator_UserTableName="Hotel">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdHotel" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdHotel" msprop:Generator_ColumnPropNameInTable="IdHotelColumn" msprop:Generator_ColumnVarNameInTable="columnIdHotel" msprop:Generator_UserColumnName="IdHotel" type="xs:int" />
              <xs:element name="HotelName" msprop:Generator_ColumnPropNameInRow="HotelName" msprop:Generator_ColumnPropNameInTable="HotelNameColumn" msprop:Generator_ColumnVarNameInTable="columnHotelName" msprop:Generator_UserColumnName="HotelName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="150" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Room" msprop:Generator_RowEvHandlerName="RoomRowChangeEventHandler" msprop:Generator_RowDeletedName="RoomRowDeleted" msprop:Generator_RowDeletingName="RoomRowDeleting" msprop:Generator_RowEvArgName="RoomRowChangeEvent" msprop:Generator_TablePropName="Room" msprop:Generator_RowChangedName="RoomRowChanged" msprop:Generator_RowChangingName="RoomRowChanging" msprop:Generator_TableClassName="RoomDataTable" msprop:Generator_RowClassName="RoomRow" msprop:Generator_TableVarName="tableRoom" msprop:Generator_UserTableName="Room">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdRoom" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdRoom" msprop:Generator_ColumnPropNameInTable="IdRoomColumn" msprop:Generator_ColumnVarNameInTable="columnIdRoom" msprop:Generator_UserColumnName="IdRoom" type="xs:int" />
              <xs:element name="Number" msprop:Generator_ColumnPropNameInRow="Number" msprop:Generator_ColumnPropNameInTable="NumberColumn" msprop:Generator_ColumnVarNameInTable="columnNumber" msprop:Generator_UserColumnName="Number" type="xs:int" />
              <xs:element name="RoomTypeId" msprop:Generator_ColumnPropNameInRow="RoomTypeId" msprop:Generator_ColumnPropNameInTable="RoomTypeIdColumn" msprop:Generator_ColumnVarNameInTable="columnRoomTypeId" msprop:Generator_UserColumnName="RoomTypeId" type="xs:int" />
              <xs:element name="HotelId" msprop:Generator_ColumnPropNameInRow="HotelId" msprop:Generator_ColumnPropNameInTable="HotelIdColumn" msprop:Generator_ColumnVarNameInTable="columnHotelId" msprop:Generator_UserColumnName="HotelId" type="xs:int" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="RoomType" msprop:Generator_RowEvHandlerName="RoomTypeRowChangeEventHandler" msprop:Generator_RowDeletedName="RoomTypeRowDeleted" msprop:Generator_RowDeletingName="RoomTypeRowDeleting" msprop:Generator_RowEvArgName="RoomTypeRowChangeEvent" msprop:Generator_TablePropName="RoomType" msprop:Generator_RowChangedName="RoomTypeRowChanged" msprop:Generator_RowChangingName="RoomTypeRowChanging" msprop:Generator_TableClassName="RoomTypeDataTable" msprop:Generator_RowClassName="RoomTypeRow" msprop:Generator_TableVarName="tableRoomType" msprop:Generator_UserTableName="RoomType">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdRoomType" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdRoomType" msprop:Generator_ColumnPropNameInTable="IdRoomTypeColumn" msprop:Generator_ColumnVarNameInTable="columnIdRoomType" msprop:Generator_UserColumnName="IdRoomType" type="xs:int" />
              <xs:element name="RoomTypeName" msprop:Generator_ColumnPropNameInRow="RoomTypeName" msprop:Generator_ColumnPropNameInTable="RoomTypeNameColumn" msprop:Generator_ColumnVarNameInTable="columnRoomTypeName" msprop:Generator_UserColumnName="RoomTypeName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="150" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Status" msprop:Generator_RowEvHandlerName="StatusRowChangeEventHandler" msprop:Generator_RowDeletedName="StatusRowDeleted" msprop:Generator_RowDeletingName="StatusRowDeleting" msprop:Generator_RowEvArgName="StatusRowChangeEvent" msprop:Generator_TablePropName="Status" msprop:Generator_RowChangedName="StatusRowChanged" msprop:Generator_RowChangingName="StatusRowChanging" msprop:Generator_TableClassName="StatusDataTable" msprop:Generator_RowClassName="StatusRow" msprop:Generator_TableVarName="tableStatus" msprop:Generator_UserTableName="Status">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IdStatus" msdata:ReadOnly="true" msdata:AutoIncrement="true" msdata:AutoIncrementSeed="-1" msdata:AutoIncrementStep="-1" msprop:Generator_ColumnPropNameInRow="IdStatus" msprop:Generator_ColumnPropNameInTable="IdStatusColumn" msprop:Generator_ColumnVarNameInTable="columnIdStatus" msprop:Generator_UserColumnName="IdStatus" type="xs:int" />
              <xs:element name="StatusName" msprop:Generator_ColumnPropNameInRow="StatusName" msprop:Generator_ColumnPropNameInTable="StatusNameColumn" msprop:Generator_ColumnVarNameInTable="columnStatusName" msprop:Generator_UserColumnName="StatusName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:Gender" />
      <xs:field xpath="mstns:IdGender" />
    </xs:unique>
    <xs:unique name="Guest_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:Guest" />
      <xs:field xpath="mstns:IdGuest" />
    </xs:unique>
    <xs:unique name="History_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:History" />
      <xs:field xpath="mstns:IdHistory" />
    </xs:unique>
    <xs:unique name="Hotel_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:Hotel" />
      <xs:field xpath="mstns:IdHotel" />
    </xs:unique>
    <xs:unique name="Room_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:Room" />
      <xs:field xpath="mstns:IdRoom" />
    </xs:unique>
    <xs:unique name="RoomType_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:RoomType" />
      <xs:field xpath="mstns:IdRoomType" />
    </xs:unique>
    <xs:unique name="Status_Constraint1" msdata:ConstraintName="Constraint1" msdata:PrimaryKey="true">
      <xs:selector xpath=".//mstns:Status" />
      <xs:field xpath="mstns:IdStatus" />
    </xs:unique>
  </xs:element>
  <xs:annotation>
    <xs:appinfo>
      <msdata:Relationship name="FK_Guest_Gender" msdata:parent="Gender" msdata:child="Guest" msdata:parentkey="IdGender" msdata:childkey="GenderId" msprop:Generator_UserParentTable="Gender" msprop:Generator_UserChildTable="Guest" msprop:Generator_RelationVarName="relationFK_Guest_Gender" msprop:Generator_ChildPropName="GetGuestRows" msprop:Generator_ParentPropName="GenderRow" msprop:Generator_UserRelationName="FK_Guest_Gender" />
      <msdata:Relationship name="FK_Guest_Status" msdata:parent="Status" msdata:child="Guest" msdata:parentkey="IdStatus" msdata:childkey="StatusId" msprop:Generator_UserParentTable="Status" msprop:Generator_UserChildTable="Guest" msprop:Generator_RelationVarName="relationFK_Guest_Status" msprop:Generator_UserRelationName="FK_Guest_Status" msprop:Generator_ChildPropName="GetGuestRows" msprop:Generator_ParentPropName="StatusRow" />
      <msdata:Relationship name="FK_History_Guest" msdata:parent="Guest" msdata:child="History" msdata:parentkey="IdGuest" msdata:childkey="GuestId" msprop:Generator_UserParentTable="Guest" msprop:Generator_UserChildTable="History" msprop:Generator_RelationVarName="relationFK_History_Guest" msprop:Generator_ChildPropName="GetHistoryRows" msprop:Generator_ParentPropName="GuestRow" msprop:Generator_UserRelationName="FK_History_Guest" />
      <msdata:Relationship name="FK_History_Room" msdata:parent="Room" msdata:child="History" msdata:parentkey="IdRoom" msdata:childkey="RoomId" msprop:Generator_UserParentTable="Room" msprop:Generator_UserChildTable="History" msprop:Generator_RelationVarName="relationFK_History_Room" msprop:Generator_UserRelationName="FK_History_Room" msprop:Generator_ChildPropName="GetHistoryRows" msprop:Generator_ParentPropName="RoomRow" />
      <msdata:Relationship name="FK_Room_Hotel" msdata:parent="Hotel" msdata:child="Room" msdata:parentkey="IdHotel" msdata:childkey="HotelId" msprop:Generator_UserParentTable="Hotel" msprop:Generator_UserChildTable="Room" msprop:Generator_RelationVarName="relationFK_Room_Hotel" msprop:Generator_ChildPropName="GetRoomRows" msprop:Generator_ParentPropName="HotelRow" msprop:Generator_UserRelationName="FK_Room_Hotel" />
      <msdata:Relationship name="FK_Room_RoomType" msdata:parent="RoomType" msdata:child="Room" msdata:parentkey="IdRoomType" msdata:childkey="RoomTypeId" msprop:Generator_UserParentTable="RoomType" msprop:Generator_UserChildTable="Room" msprop:Generator_RelationVarName="relationFK_Room_RoomType" msprop:Generator_UserRelationName="FK_Room_RoomType" msprop:Generator_ChildPropName="GetRoomRows" msprop:Generator_ParentPropName="RoomTypeRow" />
    </xs:appinfo>
  </xs:annotation>
</xs:schema>